package entity;
// Generated 21/05/2019 08:15:54 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Calificaciones generated by hbm2java
 */
public class Calificaciones  implements java.io.Serializable {


     private Integer idcal;
     private Usuarios usuarios;
     private Integer calificacion;
     private Date fecha;
     private Integer idExamen;

    public Calificaciones() {
    }

	
    public Calificaciones(Date fecha) {
        this.fecha = fecha;
    }
    public Calificaciones(Usuarios usuarios, Integer calificacion, Date fecha, Integer idExamen) {
       this.usuarios = usuarios;
       this.calificacion = calificacion;
       this.fecha = fecha;
       this.idExamen = idExamen;
    }
   
    public Integer getIdcal() {
        return this.idcal;
    }
    
    public void setIdcal(Integer idcal) {
        this.idcal = idcal;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getIdExamen() {
        return this.idExamen;
    }
    
    public void setIdExamen(Integer idExamen) {
        this.idExamen = idExamen;
    }




}


