package entity;
// Generated 21/05/2019 08:15:54 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer id;
     private String correo;
     private String nombre;
     private String passwords;
     private String tipo;
     private Set calificacioneses = new HashSet(0);

    public Usuarios() {
    }

    public Usuarios(String correo, String nombre, String passwords, String tipo, Set calificacioneses) {
       this.correo = correo;
       this.nombre = nombre;
       this.passwords = passwords;
       this.tipo = tipo;
       this.calificacioneses = calificacioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getCalificacioneses() {
        return this.calificacioneses;
    }
    
    public void setCalificacioneses(Set calificacioneses) {
        this.calificacioneses = calificacioneses;
    }




}


